apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }} 
            
          {{- if .Values.serviceAccount.create }}
          serviceAccountName: {{ .Values.serviceAccount.name }}
          {{- end }} #bind service account if create = true
          
          envFrom:
          - configMapRef:
              name: {{ .Values.name }}-config
          - secretRef:
              name: {{ .Values.name }}-secret
              