name: auth-service

replicaCount: 1

image:
  repository: 772097700150.dkr.ecr.us-east-1.amazonaws.com/natours-auth-service
  tag: latest

service:
  port: 3001

config:
  NODE_ENV: development
  PORT: "3001"
  JWT_EXPIRES_IN: "90d"
  JWT_COOKIE_EXPIRES_IN: "90"
  FRONTEND_URL: "https://your-domain.com" #change this later
  NOTIFICATION_SERVICE_URL: "http://notification-service:3005"


serviceAccount:
  create: false
  
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi