name: booking-service

replicaCount: 1

image:
  repository: 772097700150.dkr.ecr.us-east-1.amazonaws.com/natours-booking-service
  tag: latest

port: 3004

service:
  port: 3004
  
config: 
  NODE_ENV: development
  PORT: 3004
  TOUR_SERVICE_URL: http://tour-service:3002
  FRONTEND_URL: http://frontend-service:80
  AWS_REGION: us-east-1
  SQS_BOOKING_QUEUE_URL: https://sqs.us-east-1.amazonaws.com/772097700150/natours-booking-confirmed

serviceAccount:
  name: booking-service-sa
  create: true
  
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

probes:
  startup:
    create: true
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 5
    failureThreshold: 12    # 12 × 5s = 60s max startup time
    successThreshold: 1

  liveness:
    create: true
    path: /health
    initialDelaySeconds: 0
    periodSeconds: 10
    failureThreshold: 3
    successThreshold: 1
    timeoutSeconds: 5

  readiness:
    create: true
    path: /health
    initialDelaySeconds: 0
    periodSeconds: 5
    failureThreshold: 3
    successThreshold: 1
    timeoutSeconds: 3
    
autoscaling:
  create: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
