name: review-service

replicaCount: 1

image:
  repository: 772097700150.dkr.ecr.us-east-1.amazonaws.com/natours-review-service
  tag: latest

service:
  port: 3003

config:
  NODE_ENV: development
  PORT: 3003
  TOUR_SERVICE_URL: http://tour-service:3002
  AUTH_SERVICE_URL: http://auth-service:3001

serviceAccount:
  create: false